services:
  api:
    build: .
    env_file: .env
    volumes: ["./app:/code/app"]
    ports:
      - "8000:8000"
    depends_on: [redis]

  worker:
    build: .
    command: python -m app.worker
    env_file: .env
    volumes: ["./app:/code/app"]
    depends_on: [redis]

  redis:
    image: redis:7-alpine
