version: "3.9"
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes: [".:/code"]
    depends_on: [redis]
  worker:
    build: .
    command: python -m rq worker --with-scheduler
    env_file: .env
    volumes: [".:/code"]
    depends_on: [redis]
  redis:
    image: redis:7-alpine
    restart: unless-stopped
